---
title: "Manuscript 21508 - Response to review"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: word_document
bibliography: refs.bib
csl: annals-of-botany.csl
link-citations: yes
always_allow_html: true
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Editor,

Please find attached our revision of manuscript 21508. We would like to thank the handling editor Mick Hanley and the three reviewers for their constructive comments. Here is a summary of the main changes we have introduced into the text:

* We have expanded the ecological context of the study, addressing why seed traits and species ecological requirements may not correlate in these semi-natural habitats.
* We discuss how the stressors in the other habitats could explain the differential germination syndromes.
* We have revised the discussion to make it more explicit that the "domestication" is an interpretation we make after synthesizing the results (and previous research).
* We have expanded the conclusions as related to restoration, introducing the dilemma about sourcing seed from "wild" vs. "domesticated" populations.
* We have used a European-level list of mesic meadow species to get data (and conduct analysis), addressing the concern of the article conclusions being limited only to Iberia.
* We have revised the methods, indicating exactly which (and how many) data is used for each of the tests.

Below is a point-by-point response to the issues found by the reviewers. We have also included a track-changes version of the manuscript as supplementary material.

## Referee #1 

> **Despite a lot of great information provided, I believe the manuscript could be improved in several key ways before publication. First, I think the authors ought to make a stronger argument for why this study was conducted in the introduction. As written, a clear justification is lacking thus results seem to read like a case study rather than an investigation. Second, I ask the authors to more clearly state what was done and why in the methods. As written, it is tough to follow which data are being used in which analyses. Finally, I believe the authors could more clearly state why their results are novel and important throughout the discussion (i.e., why do they think traits do not map onto climate variables, what are the implications for restoration/conservation). With these improvements, I trust this will be a valuable contribution to our understanding of how seed traits can inform plant community ecology and its applications. **

Please see below comments on these various points.

> **Abstract: Overall the aim remains unclear. The methods provide more details, but why was this study done is still missing from the "background and aims" section. Consider adding a "however..." or "but..." (... data are unavailable, knowledge is lacking) statement after "...urban greening and rewilding" or a "to" statement after medic meadows". Also, the conclusion seems tangential to the results - clearer links between these two sections in the abstract would strengthen the key take-home messages of the study.**

We have added the "however" to the aims ("However, limited knowledge of species germination traits is a bottleneck to the development of a competitive native seed industry").

> **Page 2, lines 19 - 20: Consider changing "their species-rich seed mixes" to "these species-rich communities" as "seed-mix" has a specific meaning in restoration ecology.**

Changed to "These species-rich communities can be a source of seed mixes for ecological restoration".

> **Page 3, line 2: change to active voice: "Here, we synthesize..."**

Done.

> **Page 2; line 18: High germination of all seeds or poacea?**

High average germination across the species in the community, as represented by Figure 5.

> **Introduction: I think a lot of the specific details about Poaceae, Fabacea, and other family germination can be made more succinct. What are the key messages of these paragraphs - that there is high variability in germination strategies? Consider including topic sentences and conclusion sentences with selected details to make the paragraphs on germination of these groups more streamlined. **

Please see a response to a similar comment below.

> **Also, despite all of the great information provide, a compelling reason for why this study was conducted is missing. More focus on the why of the study would strengthen the introduction. In addition, hypotheses about what relationships the authors are expecting to observe would clarify for the reader why specific data were collected and methods used. Finally, hypotheses would allow the authors to more directly relate results to expectations and other research in the discussion. **

We do believe the "why" is developed in the paragraphs about the importance of meadows for European nature, and the importance of a knowledge basis for seed-based restoration. We have revised the end of the introduction to stress this. We could further rephrase the last part of the introduction into directional hypotheses, but we feel this would be untrue to the "research in context" nature of the manuscript; our goal was to provide an overview about the seed ecology of mesic meadow plants, synthesising data and published works into a coherent narrative, rather than to tests some specific hypotheses as would be the objective in a regular research paper.

> **Page 3, line 12: Consider a new sentence beginning with "during".** 

Done.

> **Page 3, line 17: real and imaged? This is confusing... **

Changed "imagined" to "fictional".

> **Page 4, line 10: Great "however" statement. Can this be made more succinct and added to the abstract? **

We have done as suggested.

> **Page 4, line 16: "framework" not needed** 

Removed.

> **Page 4, line 19: it is unclear whether the biomass is of individual poacea plants or of the whole community **

Changed to "the biomass of the community".

> **Page 5, lines 6 - 9: Are all of these references necessary? **

We agree that the references are very numerous and perhaps reiterative, however, we decided to be comprehensive because of the nature of the article as a *research in context* review hybrid. We would like potential readers to be able to access a list of references which is as complete as possible.

> **Page 4, line 10: comparatively to...?** 

To stored seeds. We added "than stored seeds".

> **Page 7, line 10: nutritional scope for which animals - insects, granivores, ungulates, all?** 

We have added "for livestock".

> **Materials and Methods: I am a bit confused about why specific treatment were done to specific groups. Justification of these methods is warranted. Also, additional clarification of specific models that were run for the different groups is needed (i.e., what are the specific fixed vs. random effects in each). Also, it remains unclear about what communities/meadows these analyses relate to - are they all for the meadows that were sampled by the authors, or are additional meadows included? **

Please see responses below. We have reformed the methods to make clearer which data is used for each test.

> **Page 10, line 19 - 22; Page 11 lines 10 -14: These sounds more like results than materials/methods13:**

These lines contain a description of part of the datasets used in the analyses. Since this description is not related to seed ecology (but to species composition), we feel it is more appropriately placed in the materials and methods.

> **Page 13, lines 1 - 5: How reliable are values obtained from these databases? Were all values for a species used, or were they filtered/limited in some way?**

The Seed Information Database provides an average value per species. For the LEDA database, we averaged all records per species. These values are reliable for broad-scale species comparisons, and are regularly used for such research.

> **Page 13; lines 12 - 16: Could these treatments affect results, especially since the same treatment was not done to every species? A comment to justify why these methods are appropriate is warranted.**

The purpose of the treatment was to measure the germination of non-dormant seeds. Since different taxonomic groups have different dormancy types, we had to adjust the treatment to the taxonomic group. We have added the sentence "This treatment was adjusted to the most probable dormancy type per taxonomic group". 

> **Page 16; line 3: Are these fixed effects for every model (poacea, fabacea, other)? From the methods, it does not seem like all treatments were applied to all groups?** 

The effects were the same for every model. Each of the three taxonomic groups had records of responses to each of the treatments. The treatments mentioned by the reviewer refer only to the Iberian germination dataset that we generated ourselves, but the models were applied to an extended dataset (our dataset + ENSCOBASE + SylvanSeeds). We have reformed the materials and methods to make clearer which data was used for each test.

> **Page 16; line 5: which variables were scaled? **

The fixed effect variables (the germination treatments). We now indicate this in the text.

> **Page 17: A clear list of which traits (and the data source) are and are not included in the PCA would be helpful.** 

We have reformed the materials and methods to make clearer which data was used for each test.

> **Page 17, lines 16 - 22: How close are these comparison communities to the ones the authors sampled? Are the authors controlling for spatial auto-correlation in any way? I am suspicious about how informative these comparisons are if other factors drive germination patterns (i.e., geography).**

All communities are from the same 75 km radius region, and the original sampled locations are interspersed, i.e. not clustered together by community (except of course the coastal communities which occur along the coast). No control was made for spatial auto-correlation, we would like to stress that this part of the analyses is only a visual analysis to further support the high germinability of meadow seeds which is found in the rest of the results (as well as the literature). See also responses regarding comments about the stressors of the different vegetation types influencing the germination patterns.

> **Discussion: I find the discussion could be improve with more narrative about why the authors findings are novel and important (see comments in introduction section). In addition, I find the results of seed traits not being related to climate quite interesting (Fig 4), but this is hardly discussed. **

We have expanded the discussion to comment on the lack of a relationship between trait variability and environment, and also on the restoration dilemma on whether to source "domesticated" or "wild" populations of meadow plants.

> **Page 22; Lines 11- 16: This ought to be broken up into two sentences to improve clarity. **

Done.

> **Page 23; lines 4 - 6 & 12 - 17 & 16 - 20: This discussion of species relationship to cold temperatures via. stratification seems contradictory to the results which found high separation of seed traits and groups from climate variables. The fact that stratification is important but seed traits were not related to climate traits makes me wonder if a mismatch exists in the traits and climate variables the authors chose to investigate? Could it be that the wrong traits were looked at or that the traits investigated align with other (unmeasured) climate variables? Additional clarification is needed here in the discussion (and in the introduction) for *why* the authors suspect these specific traits and climate variables to be related.**

One thing is that the seeds show responses to environmental cues that relate to the macroclimate of the biome in which they occur, and a different thing is that this response shows variation along climatic gradients within the biome. For example, the species of an alpine flora might all respond to cold stratification, but those species from higher elevations might require longer periods of cold stratification. We do not see the contradiction. The relationships between germination cues and climate are based on numerous references, several of which we mention in the discussion. We have expanded the discussion to comment this lack of relationship.

> **Page 23; lines 12 - 14: This sentence is confusing.** 

We have changed the sentence to "Seed germination responses to average temperatures and stratification are understood to be a mechanism to track seasonal climatic cycling ".

> **Page 24; lines 3 - 14: I recommend breaking this up into separate sentences to improve clarity.**

We have made it so.

> **Page 25; line 3: Because responses to yearly mowing were not actually tested, this remains speculative. I recommend the authors make this distinction and mention that this is a possible "selective force" in these systems, but that additional work is needed to test this hypothesis. **

We have made the suggested change.

> **Page 25; lines 9 - 12: These sentences are confusing.**

We have rephrased the sentences to attempt to make them clearer.

> **Page 25; line 21: I disagree with this statement, as this was not tested in the present study.** 

This statement is based on the interpretation of our results plus the conclusions of several of the articles cited in the discussion. We have revised the paragraph to make this clearer.

> **Figure 5: Listing the three germination treatments here in the caption would be helpful.** 

We have done so.

## Referee #2 

> **Several genera of Poaceae that grow in European meadows show seed heteromorphism (see e.g. Aegilops, Avena, Dasypirum, Poa). They produce different seed morphs characterized by different seed traits in terms of dormancy, longevity, morphology, phenology, tolerance to abiotic stresses and susceptibility to predation. This is connected to bet hedging ecological strategies, typical of ruderal/disturbed habitats. I wonder if this can be relevant also in characterizing the seed ecology of the grass species of European mesic meadows analysed by the authors. This is true also for other plant families mentioned in the paper, mainly Asteraceae.**

The reviewer raises an interesting point, we have added this to the description of seed morphology in grasses.

> **I would suggest to the authors to add brief definitions of some specialistic terms (e.g. hemiparasitic, mesic, mesophilous grasses) for the benefit of the non specialistic reader.**

We have tried to do as suggested, but the only way we have found would be to insert sentences in parentheses in the middle of other sentences, in parts of the text that are already quite dense (and one of these parts is the critical first sentence). But we think that any interested reader can find the definition of such terms easily on the internet.

> **The connection of human activities with seed ecology in mesic meadows is really interesting but I do not feel that is fully demonstrated by the results presented by the authors, appearing to me more as a speculation. The paper nicely characterizes the seed ecology of these plant communities, with comparisons with natural herbaceous communities of the same geographical area. This is to me the main focus of this study, while the supposed "domestication syndrome" of mesic meadow species appears to me as an interesting speculation. I would suggest to the authors to clarify this point and perhaps consider changing the title of the paper to better fine-tune it with the results obtained by their analysis. **

We have changed the discussion (and the title) to make clearer that the domestication is an interpretation that we derive from our results and previous articles, and that it will be necessary to do future research with the specific goal of testing it.

> **The authors rightly state that a deeper knowledge of germination ecology in mesic meadows is fundamental for a better management and conservation of this habitat and also that the dependence of these meadows on human activities highlights the importance of active restoration practices. I was wondering if the authors, based on their results, could provide more practical implications/advices for the management and seed-based restoration of this habitat that is drawing lots of attention in rewilding projects in the last few years.** 

We have expanded the discussion to address how germinability affects the ease to use meadow seeds for restoration, and also the dilemma on whether to source seeds from "domesticated" meadows or from "wild" populations of meadow species.

## Referee #3 

> **Most of the work is based on data from Iberian Peninsula and consequently, I have doubts about the possibility to extrapolate results to the rest of European meadows. For instance, one of the main conclusions is the high seed germinability of mesic meadows when compared to other herbaceous plant communities. However, this comparison is made exclusively from data of Cantabrian Mountains. Other main result is the low correspondence between seed traits and species ecological preferences, but if I have not misunderstood, both species and ecological preferences were studied only in the Iberian Peninsula. Finally, the last main result, a clear phylogenetic difference between Poaceae and Fabaceae, is not new. Authors should explain much better why their results can be extrapolated outside the Iberian Peninsula. [] One of my concerns refers to selection of species for the analyses since it was based only on relevés from Iberian Peninsula, two countries from the 32 countries included in this study. I wonder if these species are really representative of all European meadows. Maybe, authors can add some species inventories for other countries to justify the species selection.**

In the previous version, we used an Iberian species list to collect seed germination data from across Europe. In this new version, we have used a European species list to collect the data, and therefore we feel it is more extrapolable outside the Iberian Peninsula. We have repeated the germination models with the new dataset based on the European species list, and updated the results consequently (the only change is that stratification is now a not significant effect, in all models except for a negative effect in Poaceae).

> **Authors should explain how many species were analysed by the own authors and how many species were included from published databases. Furthermore, authors should give the complete reference for one of the used databases (Carta et al. 2021) (see p. 28, ln 15). A summary table with all analysed species as well as their responses to treatments, the provenance of the seeds and the corresponding reference should be included as supplementary material.**

We have included the numbers of species as requested. We have also removed the Carta reference since it is yet unpublished, and substituted it by a link to ENSCOBASE. We think the supplementary table is not necessary since the actual datasets are provided at GitHub (see the data availability section in the manuscript).

> **In addition, Poaceae and Fabaceae were considered as the two main families and the analyses and discussion were focussed on them. However, while Fabaceae included 17 % of the species, Asteraceae included 15 % (p.11 ln. 12-13) and consequently, Asteraceae should be incorporated in the study as an additional relevant plant family and not in the third minor group with the rest of the species. That is, authors should differentiate 4 botanical groups (p. 15 ln. 17). **

We see the reviewer's point, and as a matter of fact we had a separate Asteraceae group in the earliest drafts. However we decided to merge them with the rest for three reasons. (1) Even if the Asteraceae make up 15% of the species in the original list, their contribution to the meadow biomass (as seen by the relevé covers) is much smaller. (2) Furthermore, the classification in three groups follows what is traditional in grassland studies as the three groups contribute differentially to livestock nutrition (Collins, M.; Nelson, C.J.; Moore K.J. Barnes, R.B. 2020. Forages, Volume 1: An Introduction to Grassland Agriculture, 7th Edition. Wiley-Blackwell Publishing. 968 pp.). (3) And finally, separating Asteraceae would mean that the Asteraceae group would have a comparatively low record number, and make the model outputs less reliable.